services:
  consul:
    image: "consul:1.14.5"
    container_name: "consul"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - app-network

  service-discovery:
    build: ./discovery
    container_name: service-discovery
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8081:8081"
    networks:
      - app-network

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    depends_on:
      - consul
      - service-discovery
      - redis
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SERVICE_DISCOVERY_URL=http://service-discovery:8081
      - REDIS_HOST=redis

  python-microservice:
    build: ./python-microservice
    depends_on:
      - consul
      - service-discovery
    ports:
      - "8000"
    networks:
      - app-network
    deploy:
      replicas: 3
  
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
